In [5]:
from sklearn.datasets import load_wine
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from scipy import stats  # 과학용 계산 라이브러리
from sklearn.datasets import load_boston  # 사이킷런 데이타셋

# 와인 데이터를 로드한다.
wine_data = load_wine()
df_data=pd.DataFrame(wine_data.data, columns= wine_data.feature_names)
df_target=pd.DataFrame(wine_data.target, columns=["kind"])
wine= pd.concat([df_data,df_target], axis=1)

In [6]:
wine

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  kind  
0                            3.92   1065.0     0  
1                            3.40   1050.0     0  
2                            3.17   1185.0     0  
3                            3.45   1480.0     0  
4                            2.93    735.0     0  
..                            ...      ...   ...  
173                          1.74    740.0     2  
174                          1.56    750.0     2  
175                          1.56    835.0     2  
176                          1.62    840.0     2  
177                          1.60    560.0     2  

[178 rows x 14 columns]

In [4]:
wine.isnull().sum()# 결측치 제거

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
kind                            0
dtype: int64

In [43]:
#Splitting the data into training and test test
X = wine.iloc[:,0:13].values
y = wine.iloc[:,13].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values


from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [61]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(10,input_shape=(13,),activation='ReLU'))
model.add(Dense(6,activation='softmax'))
model.add(Dense(8,activation='softmax'))
model.add(Dense(3,activation='softmax'))


model.compile(Adam(lr=0.1),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_61 (Dense)            (None, 10)                140       
                                                                 
 dense_62 (Dense)            (None, 6)                 66        
                                                                 
 dense_63 (Dense)            (None, 8)                 56        
                                                                 
 dense_64 (Dense)            (None, 3)                 27        
                                                                 
Total params: 289
Trainable params: 289
Non-trainable params: 0
_________________________________________________________________


C:\Users\Cold min\anaconda3\lib\site-packages\keras\optimizers\legacy\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [62]:
#fitting the model and predicting 

# fit network
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=30,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
5/5 [==============================] - 0s 35ms/step - loss: 1.1571 - accuracy: 0.3451 - val_loss: 1.1072 - val_accuracy: 0.4444
Epoch 2/100
5/5 [==============================] - 0s 9ms/step - loss: 1.1181 - accuracy: 0.3521 - val_loss: 1.1308 - val_accuracy: 0.1667
Epoch 3/100
5/5 [==============================] - 0s 11ms/step - loss: 1.1123 - accuracy: 0.2958 - val_loss: 1.0333 - val_accuracy: 0.4444
Epoch 4/100
5/5 [==============================] - 0s 9ms/step - loss: 1.1027 - accuracy: 0.3873 - val_loss: 1.0949 - val_accuracy: 0.4444
Epoch 5/100
5/5 [==============================] - 0s 7ms/step - loss: 1.0973 - accuracy: 0.3873 - val_loss: 1.0805 - val_accuracy: 0.4444
Epoch 6/100
5/5 [==============================] - 0s 9ms/step - loss: 1.0947 - accuracy: 0.3873 - val_loss: 1.0484 - val_accuracy: 0.4444
Epoch 7/100
5/5 [==============================] - 0s 10ms/step - loss: 1.1031 - accuracy: 0.3873 - val_loss: 1.0825 - val_accuracy: 0.4444
Epoch 8/100
5/5 [=======

5/5 [==============================] - 0s 8ms/step - loss: 1.1144 - accuracy: 0.3873 - val_loss: 1.0613 - val_accuracy: 0.4444
Epoch 60/100
5/5 [==============================] - 0s 8ms/step - loss: 1.1126 - accuracy: 0.3169 - val_loss: 1.0756 - val_accuracy: 0.3889
Epoch 61/100
5/5 [==============================] - 0s 8ms/step - loss: 1.0983 - accuracy: 0.3380 - val_loss: 1.1059 - val_accuracy: 0.4444
Epoch 62/100
5/5 [==============================] - 0s 9ms/step - loss: 1.1283 - accuracy: 0.3873 - val_loss: 1.0806 - val_accuracy: 0.4444
Epoch 63/100
5/5 [==============================] - 0s 8ms/step - loss: 1.1073 - accuracy: 0.3521 - val_loss: 1.0633 - val_accuracy: 0.3889
Epoch 64/100
5/5 [==============================] - 0s 8ms/step - loss: 1.1225 - accuracy: 0.3169 - val_loss: 1.1036 - val_accuracy: 0.1667
Epoch 65/100
5/5 [==============================] - 0s 8ms/step - loss: 1.1349 - accuracy: 0.3732 - val_loss: 1.0996 - val_accuracy: 0.4444
Epoch 66/100
5/5 [===============

In [63]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.44      1.00      0.62        16
           2       0.00      0.00      0.00         6

    accuracy                           0.44        36
   macro avg       0.15      0.33      0.21        36
weighted avg       0.20      0.44      0.27        36

[[ 0 14  0]
 [ 0 16  0]
 [ 0  6  0]]


C:\Users\Cold min\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Cold min\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Cold min\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
