In [2]:
from sklearn.datasets import load_wine
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from scipy import stats  # 과학용 계산 라이브러리
from sklearn.datasets import load_boston  # 사이킷런 데이타셋

# 와인 데이터를 로드한다.
wine_data = load_wine()
df_data=pd.DataFrame(wine_data.data, columns= wine_data.feature_names)
df_target=pd.DataFrame(wine_data.target, columns=["kind"])
wine= pd.concat([df_data,df_target], axis=1)

In [3]:
wine

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  kind  
0                            3.92   1065.0     0  
1                            3.40   1050.0     0  
2                            3.17   1185.0     0  
3                            3.45   1480.0     0  
4                            2.93    735.0     0  
..                            ...      ...   ...  
173                          1.74    740.0     2  
174                          1.56    750.0     2  
175                          1.56    835.0     2  
176                          1.62    840.0     2  
177                          1.60    560.0     2  

[178 rows x 14 columns]

In [4]:
wine.isnull().sum()# 결측치 제거

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
kind                            0
dtype: int64

In [5]:
#Splitting the data into training and test test
X = wine.iloc[:,0:13].values
y = wine.iloc[:,13].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values


from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [28]:
#Defining the model 

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD,Adam
from keras.layers import Input, Dense
from keras.models import Model

# 이는 텐서를 반환합니
inputs = Input(shape=(13,))
x = Dense(10, activation='relu')(inputs)
x2 = Dense(8, activation='relu')(x)
x3 = Dense(6, activation='relu')(x2)
outputs=Dense(3,activation='softmax')(x3)

model = Model(inputs = inputs, outputs = outputs)
model.compile(Adam(lr=0.05),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_12 (InputLayer)       [(None, 13)]              0         
                                                                 
 dense_44 (Dense)            (None, 10)                140       
                                                                 
 dense_45 (Dense)            (None, 8)                 88        
                                                                 
 dense_46 (Dense)            (None, 6)                 54        
                                                                 
 dense_47 (Dense)            (None, 3)                 21        
                                                                 
Total params: 303
Trainable params: 303
Non-trainable params: 0
_________________________________________________________________


In [30]:
#fitting the model and predicting 

# fit network
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=30,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
5/5 [==============================] - 1s 48ms/step - loss: 6.5989 - accuracy: 0.3169 - val_loss: 4.7275 - val_accuracy: 0.3889
Epoch 2/100
5/5 [==============================] - 0s 6ms/step - loss: 3.9317 - accuracy: 0.3169 - val_loss: 3.0845 - val_accuracy: 0.3889
Epoch 3/100
5/5 [==============================] - 0s 10ms/step - loss: 2.5729 - accuracy: 0.3803 - val_loss: 1.8134 - val_accuracy: 0.4722
Epoch 4/100
5/5 [==============================] - 0s 11ms/step - loss: 1.4546 - accuracy: 0.5352 - val_loss: 0.9243 - val_accuracy: 0.5000
Epoch 5/100
5/5 [==============================] - 0s 10ms/step - loss: 0.9376 - accuracy: 0.5704 - val_loss: 0.8404 - val_accuracy: 0.7222
Epoch 6/100
5/5 [==============================] - 0s 9ms/step - loss: 0.9024 - accuracy: 0.5845 - val_loss: 0.8273 - val_accuracy: 0.7500
Epoch 7/100
5/5 [==============================] - 0s 8ms/step - loss: 0.8824 - accuracy: 0.5845 - val_loss: 0.8408 - val_accuracy: 0.7778
Epoch 8/100
5/5 [======

5/5 [==============================] - 0s 13ms/step - loss: 0.7482 - accuracy: 0.6408 - val_loss: 0.6593 - val_accuracy: 0.8056
Epoch 60/100
5/5 [==============================] - 0s 12ms/step - loss: 0.7475 - accuracy: 0.6268 - val_loss: 0.6724 - val_accuracy: 0.7778
Epoch 61/100
5/5 [==============================] - 0s 8ms/step - loss: 0.7492 - accuracy: 0.6197 - val_loss: 0.6724 - val_accuracy: 0.7778
Epoch 62/100
5/5 [==============================] - 0s 10ms/step - loss: 0.7369 - accuracy: 0.6408 - val_loss: 0.6523 - val_accuracy: 0.8056
Epoch 63/100
5/5 [==============================] - 0s 9ms/step - loss: 0.7462 - accuracy: 0.6408 - val_loss: 0.6508 - val_accuracy: 0.7778
Epoch 64/100
5/5 [==============================] - 0s 9ms/step - loss: 0.7378 - accuracy: 0.6338 - val_loss: 0.6521 - val_accuracy: 0.8056
Epoch 65/100
5/5 [==============================] - 0s 12ms/step - loss: 0.7347 - accuracy: 0.6338 - val_loss: 0.6504 - val_accuracy: 0.8056
Epoch 66/100
5/5 [===========

In [32]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        14
           1       0.73      1.00      0.84        16
           2       0.00      0.00      0.00         6

    accuracy                           0.81        36
   macro avg       0.55      0.64      0.59        36
weighted avg       0.68      0.81      0.74        36

[[13  1  0]
 [ 0 16  0]
 [ 1  5  0]]


C:\Users\Cold min\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Cold min\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Cold min\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
